# Generated by Django 3.2.8 on 2021-11-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Even',
            new_name='Event',
        ),
    ]
