# Generated by Django 4.0.2 on 2022-02-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_id_alter_event_id_eventschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='date',
            field=models.DateTimeField(verbose_name='Дата проведения'),
        ),
    ]
