# Generated by Django 4.0.2 on 2022-03-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_eventschedule_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventschedule',
            options={'verbose_name': 'Расписание событий', 'verbose_name_plural': 'Расписание событий'},
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время проведения'),
        ),
    ]
