# Generated by Django 4.0.3 on 2022-03-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Краткое описание'),
        ),
    ]
