# Generated by Django 2.2.25 on 2021-12-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211220_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%n/%d/', verbose_name='Фото'),
        ),
    ]
