# Generated by Django 4.0.3 on 2022-05-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category_is_active_event_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='date',
            field=models.DateField(verbose_name='Дата и время проведения'),
        ),
    ]
