# Generated by Django 4.0.3 on 2022-05-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_eventschedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='date',
            field=models.DateTimeField(unique=True, verbose_name='Дата и время проведения'),
        ),
    ]
