# Generated by Django 4.0.3 on 2022-05-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_category_name_fr_event_description_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
    ]
