# Generated by Django 4.0.3 on 2022-05-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_event_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(max_length=228),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description_en',
            field=models.CharField(max_length=228, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description_fr',
            field=models.CharField(max_length=228, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description_ru',
            field=models.CharField(max_length=228, null=True),
        ),
    ]
