# Generated by Django 4.0.3 on 2022-05-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_event_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.categorymetadata'),
        ),
    ]
