# Generated by Django 4.0.3 on 2022-05-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_event_meta_event_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='meta',
        ),
        migrations.AddField(
            model_name='categorymetadata',
            name='event',
            field=models.ManyToManyField(default=1, to='main.event'),
        ),
    ]
