# Generated by Django 4.0.3 on 2022-05-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_event_meta_categorymetadata_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymetadata',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='meta',
            field=models.ManyToManyField(default=1, to='main.categorymetadata'),
        ),
    ]
