# Generated by Django 4.0.3 on 2022-05-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_categorymetadata_event_event_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author_language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('RUS', 'Russian'), ('GER', 'German')], default='RUS', max_length=3),
        ),
    ]
