# Generated by Django 4.0.3 on 2022-05-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_event_author_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymetadata',
            name='name',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
