# Generated by Django 4.0.3 on 2022-03-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_eventinorder_options_eventinorder_nmb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventinorder',
            old_name='total_amount',
            new_name='total_price',
        ),
    ]
