# Generated by Django 4.0.3 on 2022-05-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_total_amount_eventinorder_total_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='EventOrder',
        ),
        migrations.DeleteModel(
            name='EventInOrder',
        ),
    ]
