# Generated by Django 4.0.3 on 2022-05-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_eventorder_date_alter_eventorder_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorder',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.status'),
        ),
    ]
