# Generated by Django 4.0.3 on 2022-05-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_eventorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='name_en',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='name_fr',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='name_ru',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
    ]
