# Generated by Django 4.0.3 on 2022-05-13 10:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_consultationorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultationorder',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.status'),
        ),
        migrations.AddField(
            model_name='consultationorder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
